### ISSUE TITLE
When 2 browsers are logged in as same user, delete account doesn't log out the another brower

### ISSUE THREAD

**Issue by ThomasHoooo** [CS3219-AY2324S1/ay2324s1-course-assessment-g13#39]

**Comment by rexong** [comment]
Hmmm, do you have any suggestions to remedy this? 
Cause currently delete account can only remove the cookies in the particular browser that deletes the account. 
This is aligned with HTTP Protocol where the server should remain stateless and we make the client stateful by adding the cookies. 
I cannot think of a way to automatically log the user out of the other browser, but we can probably check if the user is deleted before every request? 
Not too sure how to fix this tbh...

**Comment by ThomasHoooo** [comment]
I think everytime when we perform an api call, the jwt will be verified with the server. So if the jwt is not verified, frontend should be responsible for deleting the jwt that is stored in the browser, and log the user out. Does it make sense?

**Comment by rexong** [comment]
I dont think it is possible to check if the jwt is valid after the user deleted their accounts. I am thinking maybe we can have a middleware in go to check if the user exists, if the user dont exist, we log the user out from server side. 
The jwt cookies cannot be accessed by the frontend as the cookies are set to HTTP only, meaning only server is able to delete the cookie. This is in place for security reasons
